services:
  dboard:
    image: ghcr.io/shini74744/dboard:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/.env:/www/.env
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/data:/www/.docker/.data
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/storage/logs:/www/storage/logs
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/storage/theme:/www/storage/theme
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/storage/app:/www/storage/app
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/storage/backup:/www/storage/backup
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/public-theme:/www/public/theme
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/plugins:/www/plugins
      - ${DBOARD_DATA_DIR:-/opt/dboard/shared}/redis:/data
    environment:
      - RESOURCE_PROFILE=balanced      # minimal | balanced | performance | auto
      - ENABLE_HORIZON=true
      - docker=true

